modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/BoboTweaks/Dust-and-Ore/issues"
#clientSideOnly=true
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/BoboTweaks/Dust-and-Ore/main/update.json"
displayURL="https://github.com/BoboTweaks/Dust-and-Ore"
logoFile = "assets/dustandore/icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"