modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/BoboTweaks/Dust-and-Ore/issues"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/BoboTweaks/Dust-and-Ore/main/update.json"
displayURL="https://github.com/BoboTweaks/Dust-and-Ore"
logoFile="assets/dustandore/logo.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
ordering = "NONE"
side = "CLIENT"
